### Get all blogs
GET http://localhost:3003/api/blogs


### Create blog success
POST http://localhost:3003/api/blogs HTTP/1.1
content-Type: application/json

{  
  "title": "Blog demo title 8",
  "author": "micron",
  "url": "http://... blog",
  "likes": 1
}


### Create blog fail raise errorHandler
POST http://localhost:3003/api/blogs HTTP/1.1
content-Type: application/json

{  
  "title": "Blog demo title 2",
  "author": "micron",
  "url": "http://... blog",
  "likes": "valid number"
}


### Create user
POST http://localhost:3003/api/users HTTP/1.1
content-Type: application/json

{
  "username": "hellas",
  "name": "Arto Hellas",
  "password": "hellas"
}

### Create user
POST http://localhost:3003/api/users HTTP/1.1
content-Type: application/json

{
  "username": "mluukai",
  "name": "Matti Luukkainen",
  "password": "hashedpassword"
}

### Get Token
POST http://localhost:3003/login HTTP/1.1
content-Type: application/json

{
  "username": "hellas",
  "name": "Arto Hellas",
  "password": "hellas"
}

### Create blog with token
POST http://localhost:3003/api/blogs HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlhdCI6MTY2NjI0NzEzOX0.xtixhWjrFcHWc7hRL1cTZz5jCP1KUvwsx9n3o3ZD0Io

{  
  "title": "bloglist expansion, step7",
  "author": "micron",
  "url": "http://... blog",
  "likes": 1
}